package batch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CommandBlock_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CommandBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "batch.structure.CommandBlock";
  }
}
