package batch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ECHO_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements ICommand_BehaviorDescriptor {
  public ECHO_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "batch.structure.ECHO";
  }
}
