package batch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ECHOTO_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements ICommand_BehaviorDescriptor {
  public ECHOTO_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "batch.structure.ECHOTO";
  }
}
