package batch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;

public class FunctionsBlock_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor {
  public FunctionsBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "batch.structure.FunctionsBlock";
  }
}
