package batch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class FunctionCall_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements ICommand_BehaviorDescriptor {
  public FunctionCall_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "batch.structure.FunctionCall";
  }
}
