package batch.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.IntegerLiteral_BehaviorDescriptor;

public class IntLiteral_BehaviorDescriptor extends IntegerLiteral_BehaviorDescriptor implements IValue_BehaviorDescriptor {
  public IntLiteral_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "batch.structure.IntLiteral";
  }
}
