package batch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Params_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Params_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "batch.structure.Params";
  }
}
