package batch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class StringLiteral_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IValue_BehaviorDescriptor {
  public StringLiteral_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "batch.structure.StringLiteral";
  }
}
