package batch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class VarReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IValue_BehaviorDescriptor {
  public VarReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "batch.structure.VarReference";
  }
}
