package batch.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;

public class ICommand_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
  }
}
